### ISSUE TITLE
Remove quest issue (random)

### ISSUE THREAD

**Issue by ShadowXtrex** [dirtbikercj/TarkovTools#1]
As the title say, there is a issue when you select a mission that was added before others

example: 

mission1
mission2
mission3
mission3fix
mission4

you remove the mission3 for any reason, but the program will delete mission3fix and mission4 too

**Comment by dirtbikercj** [comment]
I cant seem to reproduce this on my end. Can you provide more information? Conditions picked, etc? Any errors in the app, or the console that launches with the app?

**Comment by dirtbikercj** [comment]
I've tested this repeatedly with different conditions, and different combinations of alphanumeric Ids. This is either an extremely rare bug or was fixed in a recent commit. 

Closing this issue for now.
